package com.ag.swagger_SpringBoot.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


//@Getter ,@Setter are used by lambok to create getter and setter
@Entity
@Table
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Book implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1670893016517855654L;
	@Id
	@GeneratedValue
	@ApiModelProperty(value = "autogenerated id")
	private int bookId;
	@ApiModelProperty(value = "this is the book name")
	private String bookName;
	@ApiModelProperty(value = "this is book price")
	private double price;
	public int getBookId() {
		// TODO Auto-generated method stub
		return bookId;
	}
	
	
}

